spring.datasource.url=jdbc:postgresql://localhost:5432/ai_backend_db
spring.datasource.username=postgres
spring.datasource.password=student

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

judge0.api.key=
judge0.api.url=http://localhost:2358/submissions?base64_encoded=false&wait=true

gemini.api.key=AIzaSyCDvDd4iGOJ-4EFF_OF-IA-0eURB00iDjo
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

server.port=8080