spring.datasource.url=jdbc:postgresql://localhost:5432/ai_backend_db
spring.datasource.username=postgres
spring.datasource.password=student

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
google.client.id=634378648722-kumbi2ql1odqdcn1gl0uhhnllija1o1s.apps.googleusercontent.com
gemini.api.key=AIzaSyC8wW84EOMCyGRmqxDJJCQjY_Jq-X8-lVY
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

server.port=8080


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.frontend.url=${FRONTEND_URL:http://localhost:3000}