spring.datasource.url=jdbc:postgresql://localhost:5432/ai_backend_db
spring.datasource.username=postgres
spring.datasource.password=student

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
google.client.id=634378648722-kumbi2ql1odqdcn1gl0uhhnllija1o1s.apps.googleusercontent.com
gemini.api.key=AIzaSyDEvVL0lPw5bOnbom4hJumLtwBFD4b0KCk
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

server.port=8080